name: CodeSniffer

on:
  push:
  pull_request:

jobs:
  cs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
        stability: [ prefer-stable ]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Install composer dependencies
        uses: nick-invision/retry@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-plugins --no-scripts --no-progress
          max_attempts: 5
          timeout_minutes: 5

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs